// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	Author      string  `json:"author"`
	Source      *Source `json:"source"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	URL         string  `json:"url"`
	URLToImage  string  `json:"urlToImage"`
	PublishedAt string  `json:"publishedAt"`
	Content     *string `json:"content"`
}

type CreateUser struct {
	Email    string    `json:"email"`
	Picture  string    `json:"picture"`
	FullName string    `json:"full_name"`
	Topics   []*string `json:"topics"`
	Password string    `json:"password"`
}

type ForgotPassword struct {
	Email string `json:"email"`
}

type GenericResponse struct {
	Message string `json:"message"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type ResetPassword struct {
	Email       string `json:"email"`
	NewPassword string `json:"newPassword"`
}

type Response struct {
	Status       string     `json:"status"`
	TotalResults int        `json:"totalResults"`
	Articles     []*Article `json:"articles"`
}

type Source struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Topic struct {
	Topic string `json:"topic"`
}

type User struct {
	ID              string   `json:"_id"`
	Email           string   `json:"email"`
	Picture         string   `json:"picture"`
	FullName        string   `json:"full_name"`
	Topics          []*Topic `json:"topics"`
	IsVerified      bool     `json:"is_verified"`
	IsOtpVerified   bool     `json:"is_otp_verified"`
	IsPasswordReset bool     `json:"is_password_reset"`
	CreatedAt       string   `json:"created_at"`
	UpdatedAt       string   `json:"updated_at"`
}

type VerifyOtp struct {
	Otp string `json:"otp"`
}
